name: portfolio

channels:
  - conda-forge

dependencies:
  - python=3.12
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scipy
  - xarray
  - netcdf4
  - h5netcdf
  - geopandas
  - cartopy
  - openpyxl
  - requests
  - pip